/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.EmployeeProfile;
import Business.Profiles.Faculty.FacultyProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class ManagePersonsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    private UserAccountDirectory userAccountDirectory;
    private ManageUserAccountsJPanel managePanel;

    public ManagePersonsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        populateComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(20, 260, 80, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Register Personnel (HR)");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jLabel3.setText("Username:");
        add(jLabel3);
        jLabel3.setBounds(180, 130, 70, 20);

        jLabel4.setText("Password:");
        add(jLabel4);
        jLabel4.setBounds(180, 170, 70, 20);

        jLabel5.setText("Role:");
        add(jLabel5);
        jLabel5.setBounds(210, 90, 42, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(260, 90, 130, 23);
        add(txtPassword);
        txtPassword.setBounds(260, 170, 130, 23);
        add(txtUsername);
        txtUsername.setBounds(260, 130, 130, 23);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(260, 220, 78, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedRole = (String) jComboBox1.getSelectedItem();
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        if (username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Person person = business.getPersonDirectory().newPerson(username);

        if (selectedRole.equals("Admin")) {
            EmployeeProfile ep = business.getEmployeeDirectory().newEmployeeProfile(person);

            UserAccount ua = new UserAccount(ep, username, password);
            business.getUserAccountDirectory().getUserAccountList().add(ua);

            ep.setUserAccount(ua);

        } else if (selectedRole.equals("Faculty")) {
            FacultyProfile fp = business.getFacultydirectory().newFacultyProfile(person);

            UserAccount ua = new UserAccount(fp, username, password);
            business.getUserAccountDirectory().getUserAccountList().add(ua);

            fp.setUserAccount(ua);

        } else if (selectedRole.equals("Student")) {
            
             StudentProfile sp = business.getStudentDirectory().newStudentProfile(person);


            UserAccount ua = new UserAccount(sp, username, password); 
            business.getUserAccountDirectory().getUserAccountList().add(ua);

            sp.setUserAccount(ua);
        }
        
         if (managePanel != null) {
        managePanel.refreshTable();
    }

    txtUsername.setText("");
    txtPassword.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void populateComboBox() {
        jComboBox1.removeAllItems();

        jComboBox1.addItem("Admin");
        jComboBox1.addItem("Faculty");
        jComboBox1.addItem("Student");
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
