/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Course.Course;
import Business.CourseSchedule.CourseOffer;
import Business.Profiles.Faculty.FacultyAssignment;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hannahchiou
 */
public class UpdateCoursesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private FacultyAssignment facultyAssignment;

    /**
     * Creates new form UpdateCoursesJPanel
     */
    public UpdateCoursesJPanel(JPanel userProcessContainer, FacultyAssignment facultyAssignment) {
        this.userProcessContainer = userProcessContainer;
        this.facultyAssignment = facultyAssignment;
        initComponents();
        loadExistingCourseData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseID = new javax.swing.JLabel();
        lblCourseCredits = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseID = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Update Course Information");

        lblCourseName.setText("Course Name");

        lblCourseID.setText("Course ID");

        lblCourseCredits.setText("Course Credits");

        btnUpdate.setText("Update Course");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCourseID)
                            .addComponent(lblCourseName)
                            .addComponent(lblCourseCredits))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCourseName)
                                .addComponent(txtCourseID)
                                .addComponent(txtCredits, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseCredits)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnUpdate)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Container parent = this.getParent();
        JPanel container = (userProcessContainer != null) ? userProcessContainer : (JPanel) parent;

        container.remove(this);

        // Refresh previous card (ManageCoursesJPanel)
        Component[] comps = container.getComponents();
        if (comps.length > 0) {
            Component prev = comps[comps.length - 1];
            if (prev instanceof ManageCoursesJPanel) {
                ((ManageCoursesJPanel) prev).refreshCourseTable();
            }
        }

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String courseName = txtCourseName.getText().trim();
        String courseId = txtCourseID.getText().trim();
        String creditsText = txtCredits.getText().trim();

        if (courseName.isEmpty() || courseId.isEmpty() || creditsText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.");
            return;
        }

        int credits;
        try {
            credits = Integer.parseInt(creditsText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Credits must be a valid whole number.");
            return;
        }

        if (credits <= 0) {
            JOptionPane.showMessageDialog(this, "Credits must be greater than 0.");
            return;
        }

        CourseOffer courseOffer = facultyAssignment.getCourseoffer();
        if (courseOffer == null || courseOffer.getSubjectCourse() == null) {
            JOptionPane.showMessageDialog(this, "Unable to update this course.");
            return;
        }

        if (hasDuplicateCourseIdInFaculty(courseId)) {
            JOptionPane.showMessageDialog(this, "Course ID already exists in your assigned courses.");
            return;
        }

        Course course = courseOffer.getSubjectCourse();
        course.setName(courseName);
        course.setNumber(courseId);
        course.setCredits(credits);

        JOptionPane.showMessageDialog(this, "Course updated successfully.");
    }//GEN-LAST:event_btnUpdateActionPerformed
    private boolean hasDuplicateCourseIdInFaculty(String courseId) {
        if (facultyAssignment == null || facultyAssignment.getFacultyProfile() == null) {
            return false;
        }

        for (FacultyAssignment assignment : facultyAssignment.getFacultyProfile().getFacultyassignments()) {
            if (assignment == facultyAssignment) {
                continue;
            }
            if (assignment.getCourseoffer() == null || assignment.getCourseoffer().getSubjectCourse() == null) {
                continue;
            }

            String existingId = assignment.getCourseoffer().getSubjectCourse().getNumber();
            if (courseId.equalsIgnoreCase(existingId)) {
                return true;
            }
        }

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCourseCredits;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCredits;
    // End of variables declaration//GEN-END:variables

    private void loadExistingCourseData() {
        if (facultyAssignment == null || facultyAssignment.getCourseoffer() == null
                || facultyAssignment.getCourseoffer().getSubjectCourse() == null) {
            return;
        }

        Course c = facultyAssignment.getCourseoffer().getSubjectCourse();
        txtCourseName.setText(c.getName());
        txtCourseID.setText(c.getNumber());
        txtCredits.setText(String.valueOf(c.getCredits()));
    }
}
