/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.Faculty.FacultyProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class CreateFacultyAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    private ManageFacultyAccountsJPanel managePanel;


    public CreateFacultyAccountJPanel(Business bz, JPanel jp, ManageFacultyAccountsJPanel mp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        this.managePanel = mp;

    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnCreateStudent = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(40, 320, 90, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Create Faculty Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jLabel1.setText("Username:");
        add(jLabel1);
        jLabel1.setBounds(150, 140, 80, 20);

        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(150, 180, 70, 20);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(230, 140, 190, 23);
        add(txtPassword);
        txtPassword.setBounds(230, 180, 190, 23);

        btnCreateStudent.setText("Create Faculty");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });
        add(btnCreateStudent);
        btnCreateStudent.setBounds(270, 230, 120, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        // TODO add your handling code here:
        
    String username = txtUsername.getText();
    String password = txtPassword.getText();


    if (username.isBlank() || password.isBlank()) { 
        JOptionPane.showMessageDialog(this, "All fields are mandatory!","Error",JOptionPane.WARNING_MESSAGE);
        return;
    }
    

    Person person = business.getPersonDirectory().newPerson(username);

    FacultyProfile fp = business.getFacultydirectory().newFacultyProfile(person);

    UserAccount ua = new UserAccount(fp, username, password); 
    business.getUserAccountDirectory().getUserAccountList().add(ua);
    
    fp.setUserAccount(ua);

    if (managePanel != null) {
        managePanel.refreshTable();
    }

    txtUsername.setText("");
    txtPassword.setText("");


    JOptionPane.showMessageDialog(this, "Faculty account created successfully!");
        
    }//GEN-LAST:event_btnCreateStudentActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
