/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Profiles.EmployeeProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageEmployeeAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    private LocalDateTime lastAccess;
    private LocalDateTime lastUpdated;


    public ManageEmployeeAccountsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();

    }

     public void refreshTable() {

    DefaultTableModel model = (DefaultTableModel) UserAccountTable.getModel();
    model.setRowCount(0); // clear table

    UserAccountDirectory uad = business.getUserAccountDirectory();

    for (UserAccount ua : uad.getUserAccountList()) {
        if (ua.getAssociatedPersonProfile() instanceof EmployeeProfile) {
            EmployeeProfile sp = (EmployeeProfile) ua.getAssociatedPersonProfile();

            Object[] row = new Object[3];
            row[0] = ua;                    // store the UserAccount, not StudentProfile
            row[1] = ua.getRole();          


            model.addRow(row);
        
        }
    }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserAccountTable = new javax.swing.JTable();
        btnDeleteStudent = new javax.swing.JButton();
        btnCreateStudent = new javax.swing.JButton();
        btnModifyStudent = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 300, 90, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Employee Accounts");
        add(jLabel1);
        jLabel1.setBounds(30, 90, 190, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Employee Accounts");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        UserAccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Status"
            }
        ));
        UserAccountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserAccountTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(UserAccountTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 510, 130);

        btnDeleteStudent.setText("Delete Employee");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });
        add(btnDeleteStudent);
        btnDeleteStudent.setBounds(400, 290, 140, 20);

        btnCreateStudent.setText("Create Employee");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });
        add(btnCreateStudent);
        btnCreateStudent.setBounds(400, 260, 140, 20);

        btnModifyStudent.setText("View Employee");
        btnModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyStudentActionPerformed(evt);
            }
        });
        add(btnModifyStudent);
        btnModifyStudent.setBounds(400, 320, 140, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void UserAccountTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserAccountTableMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        int size = UserAccountTable.getRowCount();
        int selectedrow = UserAccountTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) UserAccountTable.getValueAt(selectedrow, 0);
        if (selecteduseraccount == null) {
            return;
        }
        
        
            
    }//GEN-LAST:event_UserAccountTableMousePressed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
         int row = UserAccountTable.getSelectedRow();
        if(row < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UserAccount ua = (UserAccount) UserAccountTable.getValueAt(row, 0);

    if (ua.getAssociatedPersonProfile() instanceof EmployeeProfile) {
        EmployeeProfile ep = (EmployeeProfile) ua.getAssociatedPersonProfile();
        business.getEmployeeDirectory().removeEmployee(ep);
        business.getUserAccountDirectory().getUserAccountList().remove(ua);

        refreshTable();
        
         JOptionPane.showMessageDialog(null, "This Employee Account has been deleted", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        CreateEmployeeAccountJPanel cea = new CreateEmployeeAccountJPanel(business, CardSequencePanel,this);
        CardSequencePanel.add("Create Employee", cea);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);      
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyStudentActionPerformed
        // TODO add your handling code here:
          int row = UserAccountTable.getSelectedRow();
    if(row < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UserAccount ua = (UserAccount) UserAccountTable.getValueAt(row, 0);


    EmployeeProfile ep = (EmployeeProfile) ua.getAssociatedPersonProfile();

    ModifyEmployeeAccountJPanel viewEmployeePanel = new ModifyEmployeeAccountJPanel(business, CardSequencePanel, this, ua);

    CardSequencePanel.add("Modify Employee", viewEmployeePanel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
         
    }//GEN-LAST:event_btnModifyStudentActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable UserAccountTable;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnModifyStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
