/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Profiles.Faculty.FacultyProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageFacultyAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    private LocalDateTime lastAccess;
    private LocalDateTime lastUpdated;


    public ManageFacultyAccountsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();

    }

     public void refreshTable() {

    DefaultTableModel model = (DefaultTableModel) UserAccountTable.getModel();
    model.setRowCount(0); // clear table

    UserAccountDirectory uad = business.getUserAccountDirectory();

    for (UserAccount ua : uad.getUserAccountList()) {
        if (ua.getAssociatedPersonProfile() instanceof FacultyProfile) {
            FacultyProfile fp = (FacultyProfile) ua.getAssociatedPersonProfile();

            Object[] row = new Object[3];
            row[0] = ua;                    // store the UserAccount, not StudentProfile
            row[1] = ua.getRole();          


            model.addRow(row);
        
        }
    }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserAccountTable = new javax.swing.JTable();
        btnDeleteFaculty = new javax.swing.JButton();
        btnCreateFaculty = new javax.swing.JButton();
        btnModifyFaculty = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 300, 90, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Faculty Accounts");
        add(jLabel1);
        jLabel1.setBounds(30, 90, 190, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Faculty Accounts");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        UserAccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Status"
            }
        ));
        UserAccountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserAccountTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(UserAccountTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 510, 130);

        btnDeleteFaculty.setText("Delete Faculty");
        btnDeleteFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFacultyActionPerformed(evt);
            }
        });
        add(btnDeleteFaculty);
        btnDeleteFaculty.setBounds(420, 290, 120, 20);

        btnCreateFaculty.setText("Create Faculty");
        btnCreateFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFacultyActionPerformed(evt);
            }
        });
        add(btnCreateFaculty);
        btnCreateFaculty.setBounds(420, 260, 120, 20);

        btnModifyFaculty.setText("View Faculty");
        btnModifyFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyFacultyActionPerformed(evt);
            }
        });
        add(btnModifyFaculty);
        btnModifyFaculty.setBounds(420, 320, 120, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void UserAccountTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserAccountTableMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        int size = UserAccountTable.getRowCount();
        int selectedrow = UserAccountTable.getSelectionModel().getLeadSelectionIndex();

        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selecteduseraccount = (UserAccount) UserAccountTable.getValueAt(selectedrow, 0);
        if (selecteduseraccount == null) {
            return;
        }
        
        
            
    }//GEN-LAST:event_UserAccountTableMousePressed

    private void btnDeleteFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFacultyActionPerformed
        // TODO add your handling code here:
        int row = UserAccountTable.getSelectedRow();
        if(row < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UserAccount ua = (UserAccount) UserAccountTable.getValueAt(row, 0);

    if (ua.getAssociatedPersonProfile() instanceof FacultyProfile) {
        FacultyProfile fp = (FacultyProfile) ua.getAssociatedPersonProfile();
        business.getFacultydirectory().removeFaculty(fp);
        business.getUserAccountDirectory().getUserAccountList().remove(ua);

        refreshTable();
        
         JOptionPane.showMessageDialog(null, "This Faculty Account has been deleted", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }
        
    }//GEN-LAST:event_btnDeleteFacultyActionPerformed

    private void btnCreateFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFacultyActionPerformed
        CreateFacultyAccountJPanel cfa = new CreateFacultyAccountJPanel(business, CardSequencePanel,this);
        CardSequencePanel.add("Create Faculty", cfa);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);   
    }//GEN-LAST:event_btnCreateFacultyActionPerformed

    private void btnModifyFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyFacultyActionPerformed
     
         int row = UserAccountTable.getSelectedRow();
    if(row < 0) {
        JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UserAccount ua = (UserAccount) UserAccountTable.getValueAt(row, 0);


    FacultyProfile fp = (FacultyProfile) ua.getAssociatedPersonProfile();

    ModifyFacultyAccountJPanel viewFacultyPanel = new ModifyFacultyAccountJPanel(business, CardSequencePanel, this, ua);

    CardSequencePanel.add("Modify Faculty", viewFacultyPanel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
    }//GEN-LAST:event_btnModifyFacultyActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable UserAccountTable;
    private javax.swing.JButton btnCreateFaculty;
    private javax.swing.JButton btnDeleteFaculty;
    private javax.swing.JButton btnModifyFaculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
