/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.Faculty.FacultyProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ModifyFacultyAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;
    private ManageFacultyAccountsJPanel managePanel;
    private FacultyProfile faculty;
    private UserAccount userAccount; 



    public ModifyFacultyAccountJPanel(Business bz, JPanel jp, ManageFacultyAccountsJPanel mp,UserAccount ua) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        this.managePanel = mp;
        this.userAccount = ua; // store the UserAccount
        this.faculty = (FacultyProfile) ua.getAssociatedPersonProfile();
        loadFacultyData();
        setViewMode();

    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(40, 320, 90, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("View Employee Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jLabel1.setText("Username:");
        add(jLabel1);
        jLabel1.setBounds(150, 140, 80, 20);

        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(150, 180, 70, 20);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(230, 140, 190, 23);
        add(txtPassword);
        txtPassword.setBounds(230, 180, 190, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(220, 250, 90, 20);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(320, 250, 90, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
 //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");

    }//GEN-LAST:event_BackActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    String username = txtUsername.getText();
    String password = txtPassword.getText();

    if (username.isBlank() || password.isBlank()) { 
        JOptionPane.showMessageDialog(this, "All fields are mandatory!","Error",JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (faculty != null) {
        // Update existing
        userAccount.setUsername(username);
        userAccount.setPassword(password);

        JOptionPane.showMessageDialog(this, "Faculty account updated successfully!");
        userAccount.setLastUpdated(LocalDateTime.now());
    } 

    if (managePanel != null) {
        managePanel.refreshTable();
    }

    setViewMode();
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed
    
     private void setViewMode() {
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
      
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void setEditMode() {
        
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
    private void loadFacultyData() {
    if (faculty != null) {
        txtUsername.setText(userAccount.getUserLoginName());    // use the stored UserAccount
        txtPassword.setText(userAccount.getPassword());  
    }
}
}
