/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.LibrarianRole;

import Business.Library.Book;
import javax.swing.table.DefaultTableModel;
import Business.Business;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

import java.awt.CardLayout;
/**
 *
 * @author lajon
 */
public class ManageBooksJPanel extends javax.swing.JPanel {

    Business business;
    JPanel CardSequencePanel;
    ManageBooksJPanel parentPanel;

    public ManageBooksJPanel(Business b, JPanel jp) {
        this.business = b;
        this.CardSequencePanel = jp;
        initComponents();
        populateTable();
    }


    /**
     * Creates new form ManageBooksJPanel
     */
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        btnViewBooks = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        lblTitleBooks = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnViewBooks.setText("View Books");
        btnViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBooksActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Author Name", "Availability"
            }
        ));
        jScrollPane1.setViewportView(tblBooks);

        lblTitleBooks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleBooks.setText("Manage Books");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)
                        .addGap(119, 119, 119)
                        .addComponent(lblTitleBooks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(41, 41, 41)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addGap(45, 45, 45)
                                .addComponent(btnViewBooks))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleBooks)
                    .addComponent(btnBack))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnViewBooks))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
          AddUpdateBookJPanel panel
                = new AddUpdateBookJPanel(business,
                        CardSequencePanel,
                        null,
                        this);

        CardSequencePanel.add("AddBook", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
      
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblBooks.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a book!");
            return;
        }

        String bookId = tblBooks.getValueAt(selectedRow, 0).toString();

        Book selectedBook = null;

        for (Book book : business.getBookDirectory().getBookList()) {
            if (book.getBookId().equals(bookId)) {
                selectedBook = book;
                break;
            }
        }

        AddUpdateBookJPanel panel
                = new AddUpdateBookJPanel(business, CardSequencePanel, selectedBook, this);

        CardSequencePanel.add("UpdateBook", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBooks.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a book!");
            return;
        }

        String bookId = tblBooks.getValueAt(selectedRow, 0).toString();

        Book bookToDelete = null;

        for (Book book : business.getBookDirectory().getBookList()) {
            if (book.getBookId().equals(bookId)) {
                bookToDelete = book;
                break;
            }
        }

        if (bookToDelete != null) {

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete?",
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                business.getBookDirectory().getBookList().remove(bookToDelete);
                JOptionPane.showMessageDialog(this, "Book Deleted Successfully!");
                populateTable();
            }
        }       
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBooksActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBooks.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a book!");
            return;
        }

        String id = tblBooks.getValueAt(selectedRow, 0).toString();
        String title = tblBooks.getValueAt(selectedRow, 1).toString();
        String author = tblBooks.getValueAt(selectedRow, 2).toString();
        String status = tblBooks.getValueAt(selectedRow, 3).toString();

        JOptionPane.showMessageDialog(this,
                "Book Details:\n\n"
                + "ID: " + id + "\n"
                + "Title: " + title + "\n"
                + "Author: " + author + "\n"
                + "Status: " + status,
                "Book Information",
                JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_btnViewBooksActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "LibrarianHome"); 
    }//GEN-LAST:event_btnBackActionPerformed
        public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblBooks.getModel();
        model.setRowCount(0); // clear table

        for (Book book : business.getBookDirectory().getBookList()) {

            if (!book.isAvailable()) {
                continue;
            }

            Object[] row = new Object[4];
            row[0] = book.getBookId();
            row[1] = book.getTitle();
            row[2] = book.getAuthor();
            row[3] = "Available";

            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewBooks;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitleBooks;
    private javax.swing.JTable tblBooks;
    // End of variables declaration//GEN-END:variables
}
