/**
 *
 * @author Kenneth Garcia NUID 003166112
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Course.Course;
import Business.CourseSchedule.SeatAssignment;
import Business.Degree.Degree;
import Business.Profiles.StudentProfile;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kens2
 */
public class StudentGraduationJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel;
    StudentProfile student;
    Degree degree;
    /**
     * Creates new form StudentGraduationJPanel
     */
    public StudentGraduationJPanel(StudentProfile sp, Degree d, JPanel jp) {
        CardSequencePanel = jp;
        this.student = sp;
        this.degree = d;
        initComponents();
        loadGraduationAudit();
    }
    
    private void loadGraduationAudit() {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);
        
        // Get all courses taken
        ArrayList<SeatAssignment> allCourses = student.getCourseList();
        
        int totalCredits = 0;
        int coreCompleted = 0;
        int electivesTaken = 0;
        int totalCoreRequired = degree.corelist.size();
        
        // mark which core courses are completed
        for (Course core : degree.corelist) {
            boolean completed = false;
            String grade = "Not Taken";
            String semester = "";
            
            for (SeatAssignment sa : allCourses) {
                if (sa.getAssociatedCourse().equals(core)) {
                    completed = true;
                    grade = String.valueOf(sa.grade);
                    semester = getSemesterFromSA(sa);
                    totalCredits += sa.getCreditHours();
                    break;
                }
            }
            
            Object[] row = new Object[5];
            row[0] = core.getCOurseNumber();
            row[1] = core.getName();
            row[2] = core.getCredits();
            row[3] = completed ? grade : "Not Taken";
            row[4] = "Core";
            model.addRow(row);
            
            if (completed) coreCompleted++;
        }
        
        for (SeatAssignment sa : allCourses) {
            Course course = sa.getAssociatedCourse();
            
            boolean isCore = false;
            for (Course core : degree.corelist) {
                if (course.equals(core)) {
                    isCore = true;
                    break;
                }
            }
            
            if (!isCore) {
                Object[] row = new Object[5];
                row[0] = course.getCOurseNumber();
                row[1] = course.getName();
                row[2] = course.getCredits();
                row[3] = String.valueOf(sa.grade);
                row[4] = "ELECTIVE";
                model.addRow(row);
                
                electivesTaken++;
                totalCredits += course.getCredits();
            }
        }
        
        lblCoreProgress.setText("Core: " + coreCompleted + "/" + totalCoreRequired);
        lblElectivesProgress.setText("Electives Taken: " + electivesTaken);
        lblTotalCredits.setText("Total Credits: " + totalCredits);
        
        boolean readyToGraduate = degree.isStudentReadyToGraduate(student);
        
        if (readyToGraduate) {
            lblGraduationStatus.setText("ELIGIBLE TO GRADUATE");
        } else {
            lblGraduationStatus.setText("NOT ELIGIBLE TO GRADUATE");
        }
    }
    
    private String getSemesterFromSA(SeatAssignment sa) {
        try {
            return sa.getCourseOffer().getCourseSchedule().getSemester();
        } catch (Exception e) {
            return "Unknown";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblCoreProgress = new javax.swing.JTextField();
        lblElectivesProgress = new javax.swing.JTextField();
        lblGraduationStatus = new javax.swing.JTextField();
        lblTotalCredits = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(0, 51, 255));
        setForeground(new java.awt.Color(51, 51, 255));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Course Number", "Credits", "Grade", "Requirement"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        jLabel1.setText("Degree Evaluation");

        lblCoreProgress.setText("Core");
        lblCoreProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCoreProgressActionPerformed(evt);
            }
        });

        lblElectivesProgress.setText("Electives");

        lblGraduationStatus.setText("Graduation");

        lblTotalCredits.setText("Credits");

        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCoreProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblElectivesProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGraduationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoreProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElectivesProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGraduationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCoreProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCoreProgressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCoreProgressActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblCoreProgress;
    private javax.swing.JTextField lblElectivesProgress;
    private javax.swing.JTextField lblGraduationStatus;
    private javax.swing.JTextField lblTotalCredits;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables
}
