/**
 *
 * @author Kenneth Garcia NUID 003166112
 */
package UserInterface.WorkAreas.StudentRole;


import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import Business.Business;
import Business.Course.Course;
import Business.CourseSchedule.CourseLoad;
import Business.CourseSchedule.SeatAssignment;
import Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author kens2
 */
public class StudentCourseWorkJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel;
    CourseLoad courseLoad;
    SeatAssignment selectedSeatAssignment;
    /**
     * Creates new form StudentCourseWorkJPanel
     */
    public StudentCourseWorkJPanel(CourseLoad cl, JPanel jp) {
        CardSequencePanel = jp;
        this.courseLoad = cl;
        
        initComponents();
        refreshTable(cl);
    }
    public void refreshTable(CourseLoad cl) {
        if (cl == null) {
        System.out.println("CourseLoad is null - no coursework to display");
        return;
    }
        int rc = tblCourseLoad.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tblCourseLoad.getModel()).removeRow(i);
        }
        
        for (SeatAssignment sa : cl.getSeatAssignments()) {
            String course = sa.getCourseOffer().getCourseNumber();
            
            Object[] row = new Object[3];
            row[0] = course;
            row[1] = sa.getAssociatedCourse().getName();
            row[2] = sa;
            ((DefaultTableModel) tblCourseLoad.getModel()).addRow(row);
        }
        TableColumnModel columnModel = tblCourseLoad.getColumnModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblTblTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseLoad = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 0, 204));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblTblTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Course Work");

        tblCourseLoad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Course ID", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourseLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCourseLoadMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourseLoad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 11, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(396, 396, 396)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 84, Short.MAX_VALUE)
                    .addComponent(lblTblTitle)
                    .addGap(191, 191, 191)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(btnNext))
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //       ((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseLoad.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, 
            "Please select a course first", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    SeatAssignment selectedSA = (SeatAssignment) tblCourseLoad.getValueAt(selectedRow, 2);
    
    if (selectedSA != null) {
        // Create and add the ManageCourseJPanel
        StudentManageCourseJPanel managePanel = new StudentManageCourseJPanel(selectedSA, CardSequencePanel);
        CardSequencePanel.add(managePanel, "ManageCourse");
        
        // Switch to the new panel
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) CardSequencePanel.getLayout();
        cardLayout.next(CardSequencePanel);
    } else {
        JOptionPane.showMessageDialog(this, 
            "Error loading course details", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnNextActionPerformed

    private void tblCourseLoadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseLoadMousePressed
        // Extracts the row (uaser account) in the table that is selected by the user
        int size = tblCourseLoad.getRowCount();
        int selectedrow = tblCourseLoad.getSelectionModel().getLeadSelectionIndex();
        if (selectedrow < 0 || selectedrow > size - 1) {
            return;
        }
        selectedSeatAssignment = (SeatAssignment) tblCourseLoad.getValueAt(selectedrow, 2);
    }//GEN-LAST:event_tblCourseLoadMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTblTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourseLoad;
    // End of variables declaration//GEN-END:variables
}
